name: Frontend - Angular CI

on:
  push:
    branches: [ "main", "firebase" ]
  pull_request:
    branches: [ "main", "firebase" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm ci

      - name: Construir y correr pruebas
        run: |
          npm run test -- --watch=false --browsers=ChromeHeadless
          npm run build
